[METADATA]
modified = 2020-04-01T11:40:00.000Z

[[ACCOUNTS]]
address = "rNixerUVPwrhxGDt4UooDu6FJ7zuofvjCF"
network = "main"
desc = "nixerFFM"

[[PRINCIPALS]]
name = "XummCommunity"
email = "XummCommunity@gmail.com"
twitter = "@XummCommunity"
