[METADATA]
modified = 2021-03-05T11:40:00.000Z

[[ACCOUNTS]]
address = "rNixerUVPwrhxGDt4UooDu6FJ7zuofvjCF"
desc = "XummCommunity Main"

[[ACCOUNTS]]
address = "rELeasERs3m4inA1UinRLTpXemqyStqzwh"
desc = "XummCommunity Auto Escrow Releaser"

[[PRINCIPALS]]
name = "XummCommunity"
email = "XummCommunity@gmail.com"
twitter = "XummCommunity"
